language: node_js

node_js:
  - "15"
  - "14"
  - "12"
  - "11"

branches:
  only:
    - main
    - develop

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
